=== kisko15/B7IK21_XMLgyak/B7IK21_1012/KK_nevjegykartya.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/KK_nevjegykartya" elementFormDefault="qualified">
	<xs:element name="nevjegykartyak">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nev" type="xs:string"/>
				<xs:element name="ceg">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nev" type="xs:string"/>
								<xs:element name="cim">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="iranyitoszam" type="irszTipus"/>
											<xs:element name="varos" type="xs:string"/>
											<xs:element name="utca" type="xs:string"/>
											<xs:element name="hazszam" type="xs:integer"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							<xs:element name="telefonszam" type="xs:integer"/>
							<xs:element name="weblap" type="weblapTipus"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="beosztas" type="xs:string"/>
				<xs:element name="telefonszam" type="xs:string"/>
				<xs:element name="email" type="emailTipus"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="emailTipus">
		<xs:restriction base="xs:string">
			<xs:minLength value="10"/>
			<xs:maxLength value="25"/>
			<xs:whiteSpace value="preserve"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="weblapTipus">
		<xs:restriction base="xs:string">
			<xs:minLength value="10"/>
			<xs:maxLength value="25"/>
			<xs:whiteSpace value="preserve"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="irszTipus">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="4"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== kisko15/B7IK21_XMLgyak/B7IK21_1012/KK_nevjegykartya.xml
<?xml version="1.0" encoding="UTF-8"?>

<nevjegykartyak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KK_nevjegykartya.xsd">
	<nev>Jakab Béla</nev>
	<ceg>
		<nev>Kartyakészítő Zrt.</nev>
		<cim>
			<iranyitoszam>3665</iranyitoszam>
			<varos>Bélapátfalva</varos>
			<utca>Fő út</utca>
			<hazszam>12</hazszam>
		</cim>
		<telefonszam>06305556677</telefonszam>
		<weblap>www.kartya.hu</weblap>
	</ceg>
	<beosztas>Szállító</beosztas>
	<telefonszam>06305556688</telefonszam>
	<email>jakabBela@gmail.com</email>
</nevjegykartyak>
