=== kisko15/B7IK21_XMLgyak/B7IK21_1005/KK_konyv.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT konyvek (konyv*)>
	<!ELEMENT konyv (cim, kiadasi_ev, kiado, szerzo+, absztakt?)>
		<!ATTLIST konyv id ID #REQUIRED>
		<!ELEMENT cim (#PCDATA)>
		<!ELEMENT kiadasi_ev (#PCDATA)>
		<!ELEMENT kiado (#PCDATA)>
		<!ELEMENT szerzo (#PCDATA)>
		<!ELEMENT absztakt (#PCDATA)>

=== kisko15/B7IK21_XMLgyak/B7IK21_0928/KK_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE konyvek SYSTEM "KK_konyv.dtd">

<konyvek>
	<konyv id="KONYV_01">
		<cim>Mesterséges intelligencia</cim>
		<kiadasi_ev>1995</kiadasi_ev>
		<kiado>Mozaik</kiado>
		<szerzo>Jakab Péter</szerzo>
		<absztakt>AB1</absztakt>
	</konyv>
	<konyv id="KONYV_2">
		<cim>Információs rendszerek</cim>
		<kiadasi_ev>1997</kiadasi_ev>
		<kiado>Mozaik2</kiado>
		<szerzo>Kocsis István</szerzo>
		<absztakt>AB2</absztakt>
	</konyv>
</konyvek>

=== kisko15/B7IK21_XMLgyak/B7IK21_1005/KK_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KK_konyv.xsd">

<!-- <!DOCTYPE konyvek SYSTEM "KK_konyv.dtd">  -->

	<konyv id="KONYV_01">
		<cim>Mesterséges intelligencia</cim>
		<kiadasi_ev>1995</kiadasi_ev>
		<kiado>Mozaik</kiado>
		<szerzo>Jakab Péter</szerzo>
		<absztakt>AB1</absztakt>
	</konyv>
	
	<konyv id="KONYV_2">
		<cim>Információs rendszerek</cim>
		<kiadasi_ev>1997</kiadasi_ev>
		<kiado>Mozaik2</kiado>
		<szerzo>Kocsis István</szerzo>
		<absztakt>AB2</absztakt>
	</konyv>
</konyvek>
