<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE er [
	<!ELEMENT er (A*, B*, C*, A_B*)>
		<!ELEMENT A (Ab*, Ac)>
		<!ATTLIST A Aa ID #REQUIRED>
			<!ELEMENT Ab (Abx, Aby)>
				<!ELEMENT Abx ( #PCDATA )>
				<!ELEMENT Aby ( #PCDATA )>
			<!ELEMENT Ac (Acd, Ace)>
				<!ELEMENT Acd ( #PCDATA )>
				<!ELEMENT Ace ( #PCDATA )>
		<!ELEMENT B (Bb)>
		<!ATTLIST B Ba ID #REQUIRED>
		<!ATTLIST B Bc IDREF #IMPLIED>
			<!ELEMENT Bb (Bbx, Bby)>
				<!ELEMENT Bbx ( #PCDATA )>
				<!ELEMENT Bby ( #PCDATA )>
		<!ELEMENT C (Cb)>
		<!ATTLIST C Ca ID #REQUIRED>
			<!ELEMENT Cb ( #PCDATA )>
		<!ELEMENT A_B (A_Bc)>
		<!ATTLIST A_B A_B_a IDREF #IMPLIED>
		<!ATTLIST A_B A_B_b IDREF #IMPLIED>
			<!ELEMENT A_Bc ( #PCDATA )>
]>

<er>
	<A Aa="NK001">
		<Ab>
			<Abx></Abx>
			<Aby></Aby>
		</Ab>
		<Ac>
			<Acd></Acd>
			<Ace></Ace>
		</Ac>
	</A>
	<B Ba="NK002" Bc="NK001">
		<Bb>
			<Bbx></Bbx>
			<Bby></Bby>
		</Bb>
	</B>
	<C Ca="NK003">
		<Cb></Cb>
	</C>
	<A_B A_B_a="NK001" A_B_b="NK002">
		<A_Bc></A_Bc>
	</A_B>
</er>